In [1]:
import tensorflow as tf

C:\Users\Rahul\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.9.0


In [3]:
hello=tf.constant('Hello')
world=tf.constant('world')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
with tf.Session() as sess:
    result=sess.run(hello+world)

In [9]:
print(result) # b is here to represent byte leterals

b'Helloworld'


In [57]:
a=tf.constant(10)
b=tf.constant(20)

In [58]:
type(a)

tensorflow.python.framework.ops.Tensor

In [61]:
add=a+b

In [62]:
with tf.Session() as sess:
    #result=sess.run(a+b)
    result=add.eval()

In [63]:
result

30

In [17]:
const=tf.constant(10)

In [18]:
fill_mat=tf.fill((4,4),10)

In [19]:
myzeros=tf.zeros((4,4))

In [20]:
myones=tf.ones((4,4))

In [21]:
myrandn=tf.random_normal((4,4),mean=0,stddev=1)

In [22]:
myrandu=tf.random_uniform((4,4),minval=0,maxval=1)

In [23]:
my_ops=[const,fill_mat,myzeros,myones,myrandn,myrandu]

In [38]:
sess=tf.InteractiveSession() # for interative session useful in jupyter notebook

C:\Users\Rahul\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1714: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [39]:
for op in my_ops:
    print(sess.run(op)) #can use print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.82872325 -0.8049402   0.61939615  0.29848826]
 [ 0.6083762   0.31623137  0.74938786  2.0073287 ]
 [-1.1572219   0.35885927  0.08939233  0.36203673]
 [ 0.64450884 -0.19134352 -0.6341865  -0.08354989]]


[[0.200755   0.53013694 0.32169378 0.8853729 ]
 [0.27410746 0.12187111 0.97227085 0.4358425 ]
 [0.56565    0.07252669 0.06360793 0.12570798]
 [0.8604114  0.39622462 0.19720209 0.45109951]]




In [40]:
a=tf.constant([[1,2],[3,4]])

In [41]:
a.shape

TensorShape([Dimension(2), Dimension(2)])

In [42]:
b=tf.constant([[10],[100]])

In [43]:
b.shape

TensorShape([Dimension(2), Dimension(1)])

In [44]:
result=tf.matmul(a,b)

In [45]:
sess.run(result)

array([[210],
       [430]])

In [46]:
result.eval()

array([[210],
       [430]])