In [3]:
import numpy as np
import tensorflow as tf

C:\Users\Rahul\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
my_array=np.array([1,2,3])
print(my_array.shape)

(3,)


In [5]:
tensor=tf.convert_to_tensor(my_array,tf.float64)

In [6]:
with tf.Session() as sess:
    print(sess.run(tensor))

[1. 2. 3.]


In [7]:
a=tf.constant([1,2,3],tf.float32)
b=tf.constant([4,5,6],tf.float32)

In [8]:
c=a+b

In [9]:
with tf.Session() as sess:
    print(sess.run(c))

[5. 7. 9.]


In [10]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
t1=tf.convert_to_tensor(arr1,tf.float64)
t2=tf.convert_to_tensor(arr2,tf.float64)

In [12]:
t3=tf.matmul(t1,t2)

In [13]:
print(t3)

Tensor("MatMul:0", shape=(2, 3), dtype=float64)


In [14]:
with tf.Session() as sess:
    print(sess.run(t3))

[[30. 36. 42.]
 [66. 81. 96.]]


In [15]:
t4=tf.matrix_determinant(t2)

In [16]:
with tf.Session() as sess:
    print(sess.run(t4))

6.66133814775094e-16


In [36]:
import pandas as pd

In [37]:
df=pd.read_csv("../Machine learning/Iris.csv")

In [38]:
df.keys()

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [39]:
feature_columns=[]
for key in df.keys():
    if key=='Id':
        continue
    if key=='Species':
        continue
    feature_columns.append(tf.contrib.layers.feature_column.real_valued_column(key))

In [40]:
feature_columns

[_RealValuedColumn(column_name='SepalLengthCm', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='SepalWidthCm', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='PetalLengthCm', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='PetalWidthCm', dimension=1, default_value=None, dtype=tf.float32, normalizer=None)]

In [41]:
#1feature_columns=[PL,PW,SL,PW]
#2.

In [42]:
estimator=tf.estimator.DNNClassifier(feature_columns=feature_columns,hidden_units=[10],n_classes=3)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\Rahul\\AppData\\Local\\Temp\\tmp06t1c06z', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001F84BEAB160>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [48]:
import sklearn
import sklearn.model_selection

In [49]:
def my_input_fn():
    df=pd.read_csv("../Machine Learning/Iris.csv")
    df=df.drop(['Id'],axis=1)
    #y=df["Species"]
    y=pd.Categorical(df['Species']).codes
    print(y)
    y=np.array(y,dtype=np.int32)
    df=df.drop(['Species'],axis=1)
    x=df
    
    x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.2)
    
    return x_train,x_test,y_train,y_test

In [54]:
my_input_fn()

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


(     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
 18             5.7           3.8            1.7           0.3
 57             4.9           2.4            3.3           1.0
 132            6.4           2.8            5.6           2.2
 127            6.1           3.0            4.9           1.8
 40             5.0           3.5            1.3           0.3
 100            6.3           3.3            6.0           2.5
 96             5.7           2.9            4.2           1.3
 62             6.0           2.2            4.0           1.0
 146            6.3           2.5            5.0           1.9
 41             4.5           2.3            1.3           0.3
 90             5.5           2.6            4.4           1.2
 111            6.4           2.7            5.3           1.9
 145            6.7           3.0            5.2           2.3
 51             6.4           3.2            4.5           1.5
 135            7.7           3.0            6.1       

In [57]:
#estimator.train(input_fn=my_input_fn,steps=200)
X_TRAIN,X_TEST,Y_TRAIN,Y_TEST=my_input_fn()
def my_input_fn_test():
    return dict(X_TEST),Y_TEST

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [58]:
#estimator.evaluate(input_fn=my_input_fn,steps=1)
def my_train_input_fn():
    return dict(X_TRAIN),Y_TRAIN

In [61]:
estimator.train(input_fn=my_train_input_fn,steps=100)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Rahul\AppData\Local\Temp\tmp06t1c06z\model.ckpt-2
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 2 into C:\Users\Rahul\AppData\Local\Temp\tmp06t1c06z\model.ckpt.
INFO:tensorflow:loss = 137.31711, step = 3
INFO:tensorflow:Saving checkpoints for 102 into C:\Users\Rahul\AppData\Local\Temp\tmp06t1c06z\model.ckpt.
INFO:tensorflow:Loss for final step: 27.270283.


In [62]:
estimator.evaluate(input_fn=my_input_fn_test,steps=1)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-07-13-07:57:59
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Rahul\AppData\Local\Temp\tmp06t1c06z\model.ckpt-102
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2018-07-13-07:57:59
INFO:tensorflow:Saving dict for global step 102: accuracy = 0.93333334, average_loss = 0.24648617, global_step = 102, loss = 7.394585
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 102: C:\Users\Rahul\AppData\Local\Temp\tmp06t1c06z\model.ckpt-102


{'accuracy': 0.93333334,
 'average_loss': 0.24648617,
 'loss': 7.394585,
 'global_step': 102}

In [63]:
# for titanic

In [109]:
df=pd.read_csv("../Machine Learning/traintitanic.csv")

In [110]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [111]:
df=df.drop(["PassengerId","Fare","Ticket","Name","Cabin"],axis=1)
df=df.join(pd.get_dummies(df['Sex']))
df=df.drop(["Sex"],axis=1)
df=df.join(pd.get_dummies(df['Embarked']))
df=df.drop(["Embarked"],axis=1)
df=df.drop(['female'],axis=1)

In [112]:
df=df.drop(['C'],axis=1)

In [113]:
df=df.dropna()

In [114]:
type(y)

pandas.core.frame.DataFrame

In [115]:
df.keys()

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'male', 'Q', 'S'], dtype='object')

In [116]:
feature_columns=[]
for key in df.keys():
    if key=='Survived':
        continue
    feature_columns.append(tf.contrib.layers.feature_column.real_valued_column(key))

In [117]:
feature_columns

[_RealValuedColumn(column_name='Pclass', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='Age', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='SibSp', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='Parch', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='male', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='Q', dimension=1, default_value=None, dtype=tf.float32, normalizer=None),
 _RealValuedColumn(column_name='S', dimension=1, default_value=None, dtype=tf.float32, normalizer=None)]

In [137]:
def my_input_fn1():
    df=pd.read_csv("../Machine Learning/traintitanic.csv")
    df=df.drop(["PassengerId","Fare","Ticket","Name","Cabin"],axis=1)
    df=df.join(pd.get_dummies(df['Sex']))
    df=df.drop(["Sex"],axis=1)
    df=df.join(pd.get_dummies(df['Embarked']))
    df=df.drop(["Embarked"],axis=1)
    df=df.drop(['female'],axis=1)
    df=df.drop(['C'],axis=1)
    df=df.dropna()
    y=df["Survived"]
    #y=pd.Categorical(df['Species']).codes
    #print(y)
    y=np.array(y,dtype=np.int32)
    df=df.drop(['Survived'],axis=1)
    x=df
    
    x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.2)
    
    return x_train,x_test,y_train,y_test

In [142]:
estimator=tf.estimator.DNNClassifier(feature_columns=feature_columns,hidden_units=[20,20],n_classes=2)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\Rahul\\AppData\\Local\\Temp\\tmp8az_4aej', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001F84D564CF8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [143]:
X_TRAIN,X_TEST,Y_TRAIN,Y_TEST=my_input_fn()
def my_input_fn_test():
    return dict(X_TEST),Y_TEST
#estimator.evaluate(input_fn=my_input_fn,steps=1)
def my_train_input_fn():
    return dict(X_TRAIN),Y_TRAIN

In [144]:
estimator.train(input_fn=my_train_input_fn,steps=300)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Rahul\AppData\Local\Temp\tmp8az_4aej\model.ckpt.
INFO:tensorflow:loss = 406.90674, step = 1
INFO:tensorflow:global_step/sec: 398.098
INFO:tensorflow:loss = 290.92407, step = 101 (0.251 sec)
INFO:tensorflow:global_step/sec: 594.439
INFO:tensorflow:loss = 252.22069, step = 201 (0.168 sec)
INFO:tensorflow:Saving checkpoints for 300 into C:\Users\Rahul\AppData\Local\Temp\tmp8az_4aej\model.ckpt.
INFO:tensorflow:Loss for final step: 235.32831.


In [145]:
estimator.evaluate(input_fn=my_input_fn_test,steps=1)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-07-13-08:40:24
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Rahul\AppData\Local\Temp\tmp8az_4aej\model.ckpt-300
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2018-07-13-08:40:25
INFO:tensorflow:Saving dict for global step 300: accuracy = 0.7622378, accuracy_baseline = 0.5874126, auc = 0.8304076, auc_precision_recall = 0.7868768, average_loss = 0.51706535, global_step = 300, label/mean = 0.4125874, loss = 73.940346, precision = 0.6923077, prediction/mean = 0.45489678, recall = 0.7627119
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 300: C:\Users\Rahul\AppData\Local\Temp\tmp8az_4aej\model.ckpt-300


{'accuracy': 0.7622378,
 'accuracy_baseline': 0.5874126,
 'auc': 0.8304076,
 'auc_precision_recall': 0.7868768,
 'average_loss': 0.51706535,
 'label/mean': 0.4125874,
 'loss': 73.940346,
 'precision': 0.6923077,
 'prediction/mean': 0.45489678,
 'recall': 0.7627119,
 'global_step': 300}